version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - npm uninstall $(jq -r '.devDependencies | keys | join(" ")' < package.json)
      # - npm uninstall @sentry/nestjs @sentry/profiling-node @sentry/webpack-plugin

  post_build:
    commands:
      - npm install -g serverless
      - npm install --save-dev serverless-jetpack serverless-offline
      - serverless deploy --stage dev --region 'eu-central-1'

artifacts:
  files:
    - '**/*'
    - '!node_modules/'
